### ISSUE TITLE
Récupérer le format de fichier des voeux AFFLENET et PARCOURSUP coté LBA

### ISSUE THREAD

**Issue by antoinebigard** [mission-apprentissage/bal#23]
Specs notion

**Comment by david-nathanael** [comment]
Affelnet (format 2022) ✅

**Comment by Anne-Camille** [comment]
Si besoin  (fichier json)
    
    Académie possédant le dossier élève;INE;Nom de l'élève;Prénom 1;Prénom 2;Prénom 3;Adresse de l'élève - Ligne 1;Adresse de l'élève - Ligne 2;Adresse de l'élève - Ligne 3;Adresse de l'élève - Ligne 4;Code postal;VILLE;PAYS;Téléphone personnel;Téléphone professionnel;Téléphone portable;Téléphone responsable 1;Téléphone responsable 2;Mail responsable 1;Mail responsable 2;Mnémonique MEF origine de l'élève;Code Spécialité du MEF origine de l'élève;Libellé formation origine de l'élève;Code Option 1 d'origine de l'élève;Libellé Option 1 d'origine de l'élève;Code Option 2 d'origine de l'élève;Libellé Option 2 d'origine de l'élève;Code LV1 d'origine de l'élève;Libellé LV1 origine de l'élève;Code LV2 d'origine de l'élève;Libellé LV2 origine de l'élève;Code UAI étab. origine;Type étab. origine;Libellé étab. origine;Ville étab. origine;Code UAI CIO origine;Libellé CIO origine;Rang du vœu;Code offre de formation (vœu);Code MEF;Avec barème ?;Mnémonique MEF de l'offre de formation;Code spécialité de l'offre de formation;Libellé formation;Code Enseignement Optionnel;Libellé Enseignement Optionnel;Dossier de candidature en internat demandé ?;Code LV1 demandée;Libellé LV1 demandée;Code LV2 demandée;Libellé LV2 demandée;Code UAI étab. Accueil;Type étab. Accueil;Libellé établissement Accueil;Ville étab. Accueil;SIRET UAI gestionnaire;clé ministère éducatif
    
    Aix-Marseille;090482844BH;PETEL;Quentin;;;;;La Chaussée;;44520;MOISDON-LA-RIVIERE;FRANCE;33632526275;;;;;;;3EULIS;;3EME ULIS;;;;;AGL1;ANGLAIS LV1;ESP2;ESPAGNOL LV2;0840006A;COLLEGE;VIALA;AVIGNON;0840047V;CIO ETAT AVIGNON;6;APP11394;
    
    Voeu :
    
    24125434210;Non;1CAP2;25434;1CAP2 REPARATION DES CARROSSERIES;;;Non;AGL1;ANGLAIS LV1;ESP2;ESPAGNOL LV2;0840042P;LP;ROBERT SCHUMAN;AVIGNON CEDEX 2;19840005300023;053381P012X1984000530002319840042600013-84007#L01
